// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// import PdfViewerController from "./pdf_viewer_controller"
// application.register("pdf-viewer", PdfViewerController)

import DragDropController from "./drag_drop_controller"
application.register("drag-drpo", DragDropController)

import SaveHtmlController from "./save_html_controller"
application.register("svae-html", SaveHtmlController)